#!/bin/sh  
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=0
#SBATCH --partition=dcgp_usr_prod
#SBATCH --account=uTS25_Tornator_0
#SBATCH --time=00:10:00
#SBATCH --job-name=serial_stencil
##SBATCH --exclusive

EXEC=stencil_serial

# =======================================================

module load gcc/12.2.0
module load openmpi/4.1.6--gcc--12.2.0

echo "Running serial stencil job..."

./${EXEC} -x 2000 -y 2000 -n 100 > out_serial.txt
